INSERT INTO properties(id,application,profile,label,akey,avalue) VALUES (1, 'fpg-api', 'dev', 'master', 'type', 'com.zaxxer.hikari.HikariDataSource');
INSERT INTO properties(id,application,profile,label,akey,avalue) VALUES (2, 'fpg-api', 'dev', 'master', 'driverClassName', 'org.h2.Driver');
INSERT INTO properties(id,application,profile,label,akey,avalue) VALUES (3, 'fpg-api', 'dev', 'master', 'url', 'jdbc:h2:file:D:/software/data/h2/apidb;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE');
INSERT INTO properties(id,application,profile,label,akey,avalue) VALUES (4, 'fpg-api', 'dev', 'master', 'username', 'sa');
INSERT INTO properties(id,application,profile,label,akey,avalue) VALUES (5, 'fpg-api', 'dev', 'master', 'password', 'sa');
INSERT INTO properties(id,application,profile,label,akey,avalue) VALUES (6, 'fpg-api', 'dev', 'master', 'miniIdle', '5');
INSERT INTO properties(id,application,profile,label,akey,avalue) VALUES (7, 'fpg-api', 'dev', 'master', 'maxPoolSize', '50');
INSERT INTO properties(id,application,profile,label,akey,avalue) VALUES (8, 'fpg-api', 'dev', 'master', 'idleTimeout', '180000');
INSERT INTO properties(id,application,profile,label,akey,avalue) VALUES (9, 'fpg-api', 'dev', 'master', 'connectionTimeout', '30000');

INSERT INTO common_config_properties(id,application_name,config_profile,config_label,config_key,config_value) VALUES (1, 'fpg-api', 'dev', 'master', 'type', 'com.zaxxer.hikari.HikariDataSource');
INSERT INTO common_config_properties(id,application_name,config_profile,config_label,config_key,config_value) VALUES (2, 'fpg-api', 'dev', 'master', 'driverClassName', 'org.h2.Driver');
INSERT INTO common_config_properties(id,application_name,config_profile,config_label,config_key,config_value) VALUES (3, 'fpg-api', 'dev', 'master', 'url', 'jdbc:h2:file:D:/software/data/h2/apidb;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE');
INSERT INTO common_config_properties(id,application_name,config_profile,config_label,config_key,config_value) VALUES (4, 'fpg-api', 'dev', 'master', 'username', 'sa');
INSERT INTO common_config_properties(id,application_name,config_profile,config_label,config_key,config_value) VALUES (5, 'fpg-api', 'dev', 'master', 'password', 'sa');
INSERT INTO common_config_properties(id,application_name,config_profile,config_label,config_key,config_value) VALUES (6, 'fpg-api', 'dev', 'master', 'miniIdle', '5');
INSERT INTO common_config_properties(id,application_name,config_profile,config_label,config_key,config_value) VALUES (7, 'fpg-api', 'dev', 'master', 'maxPoolSize', '50');
INSERT INTO common_config_properties(id,application_name,config_profile,config_label,config_key,config_value) VALUES (8, 'fpg-api', 'dev', 'master', 'idleTimeout', '180000');
INSERT INTO common_config_properties(id,application_name,config_profile,config_label,config_key,config_value) VALUES (9, 'fpg-api', 'dev', 'master', 'connectionTimeout', '30000');
