version: "2"
services:
  eureka-server1:
    image: fpg-gateway
    container_name: fpg-gateway1
    hostname: fpg-gateway1
    ports:
      - 8001:8001
    environment:
      - SERVER_PORT=8761
      - SERVICE_NAME=fpg-gateway
      - HOSTNAME=fpg-gateway1
      - EUREKA_SERVER=http://192.168.56.11:8761/eureka,http://192.168.56.11:8762/eureka

  eureka-server2:
    image: fpg-gateway
    container_name: fpg-gateway2
    hostname: fpg-gateway2
    ports:
      - 8002:8001
    environment:
      - SERVER_PORT=8761
      - SERVICE_NAME=fpg-gateway
      - HOSTNAME=fpg-gateway2
      - EUREKA_SERVER=http://192.168.56.11:8761/eureka,http://192.168.56.11:8762/eureka