server:
  port: 8080
  
spring:
  datasource:
     url: jdbc:mysql://localhost:3306/umpdb?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
     username: umpapp
     password: ump@2019
     driverClassName: com.mysql.cj.jdbc.Driver
     type: com.alibaba.druid.pool.DruidDataSource
     master:
        url: jdbc:mysql://localhost:3306/sysdb?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
        username: umpapp
        password: ump@2019
        driverClassName: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
     slave:
        url: jdbc:mysql://localhost:3306/umpdb?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
        username: umpapp
        password: ump@2019
        driverClassName: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
     cache: false
     prefix: classpath:/templates/
     suffix: .html
  messages:
     basename: i18n.messages
#mybatis plus
mybatis:
  mapperLocations:classpath*:*com/ump/**/mapper/**/*.xml
  typeAliasesPackage:com.ump.**.entity
mybatis-plus:
  configuration:
     map-underscore-to-camel-case: true
     cache-enabled: false
  global-config:
     db-column-underline: true
     id-type: 2
     field-strategy: 2
     logic-delete-value: 0
     logic-not-delete-value: 1
     db-type: mysql
     refresh: false 
  
#logging
logging:
  level:
     com.ump.uias.modules.system.mapper: DEBUG
     com.ump.core.modules.system.mapper: DEBUG