server:
  port: 5000
spring:
  datasource:
    url: jdbc:h2:file:./DB
  batch:
    job:
      enabled:false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto:update